In [32]:
import pickle
import numpy as np

In [33]:
ohe_embarked=pickle.load(open('ohe_embarked.pkl', 'rb'))
ohe_sex=pickle.load(open('ohe_sex.pkl', 'rb'))
clf=pickle.load(open('clf.pkl', 'rb'))

In [34]:
test_input=np.array([2, 'male', 31.0, 0, 10.5, 50.0, 'S'], dtype=object).reshape(1,7)

In [35]:
test_input

array([[2, 'male', 31.0, 0, 10.5, 50.0, 'S']], dtype=object)

In [36]:
test_input_sex=ohe_sex.transform(test_input[:,1].reshape(1,1))

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [37]:
test_input_sex

array([[0., 1.]])

In [38]:
test_input_embarked=ohe_embarked.transform(test_input[:,-1].reshape(1,1))
test_input_embarked

array([[0., 0., 1.]])

In [39]:
test_input_age=test_input[:,2].reshape(1,1)
test_input_age

array([[31.0]], dtype=object)

In [40]:
rmed=np.concatenate((test_input[:,[0,3,4,5]], test_input_age, test_input_sex, test_input_embarked), axis=1)

In [41]:
rmed.shape

(1, 10)

In [42]:
clf.predict(rmed)

array([0])